### ISSUE TITLE
Be able to change the "pm open" command

### ISSUE THREAD

**Issue by filveith** [alexis-moins/pm#1]
I'm not using tmux, so it would be great to be able to change the "pm open" call

**Comment by alexis-moins** [comment]
Hello!

I added a way to execute custom hooks when using `pm open` and `pm new` commands. The hooks are identical to templates found under the [templates](https://github.com/alexis-moins/pm/tree/main/templates) directory.

For example, if you want to open the projects in vscode, you can add the following additional configuration to your `~/.config/pm/config.json`:

```json
"commands": {
  "open": {
    "tmux": false,
    "hook": [
      {
        "command": ["code", "."],
        "dir": "PROJECT"
      }
    ]
  },
  "new": {
    "tmux": false,
    "hook": [
      {
        "command": ["code", "."],
        "dir": "PROJECT"
      }
    ]
  }
}
```

Tell me if you need anything else.
Cheers

**Comment by filveith** [comment]
Hi @alexis-moins !

Thanks for the quick response and rapid change ! 
I will try that right away. I haven't seen any mention of how to update the package, I suppose I just need to do `go install github.com/alexis-moins/pm@latest`

Cheers :wave:

**Comment by alexis-moins** [comment]
Exactly! You also have the possibility to install a specific version (based on git tags). The version with the feature is `0.7.1`.

**Comment by filveith** [comment]
Nice, thanks ! It is working flawlessly
