### ISSUE TITLE
Be able to clone from other remotes than just guthub

### ISSUE THREAD

**Issue by filveith** [alexis-moins/pm#3]
Hi @alexis-moins 

I need to clone repositories from Bitbucket or GitLab for example.
Here is an example for BitBucket  **git@bitbucket.org:_organisation_/_repository.git_**

Thanks !

**Comment by alexis-moins** [comment]
Hey @filveith, I tried to fix the issue on the branch `3-be-able-to-clone-from-other-remotes-than-just-guthub`. Unfortunately, I don't have bitbucket repositories. Would you mind pulling the branch and testing if it works?

**Comment by filveith** [comment]
Okay I will test it and send you message once done 👍

**Comment by filveith** [comment]
Tested and it works ! Thanks @alexis-moins
